// AUTO-GENERATED by npm run generate:section-thumbnails
export const pageBuilderThumbnailManifest: {
  generated: Record<string, string>
  overrides: Record<string, string>
} = {
  generated: {
    "callToAction": '/static/page-builder-thumbnails/generated/callToAction.png',
    "homeCaseStudiesSection": '/static/page-builder-thumbnails/generated/homeCaseStudiesSection.png',
    "homeContactSection": '/static/page-builder-thumbnails/generated/homeContactSection.png',
    "homeFaqSection": '/static/page-builder-thumbnails/generated/homeFaqSection.png',
    "homeHeroSection": '/static/page-builder-thumbnails/generated/homeHeroSection.png',
    "homeLegacyHeroSection": '/static/page-builder-thumbnails/generated/homeLegacyHeroSection.png',
    "homeLegacyLogoBarSection": '/static/page-builder-thumbnails/generated/homeLegacyLogoBarSection.png',
    "homeLegacyOfferSection": '/static/page-builder-thumbnails/generated/homeLegacyOfferSection.png',
    "homeLegacyPricingSection": '/static/page-builder-thumbnails/generated/homeLegacyPricingSection.png',
    "homeLegacyTestimonialSection": '/static/page-builder-thumbnails/generated/homeLegacyTestimonialSection.png',
    "homeLegacyWorkSection": '/static/page-builder-thumbnails/generated/homeLegacyWorkSection.png',
    "homeLogosSection": '/static/page-builder-thumbnails/generated/homeLogosSection.png',
    "homeOfferSection": '/static/page-builder-thumbnails/generated/homeOfferSection.png',
    "homeProblemSection": '/static/page-builder-thumbnails/generated/homeProblemSection.png',
    "homeRoiSection": '/static/page-builder-thumbnails/generated/homeRoiSection.png',
    "homeUseCasesSection": '/static/page-builder-thumbnails/generated/homeUseCasesSection.png',
    "infoSection": '/static/page-builder-thumbnails/generated/infoSection.png',
  },
  overrides: {

  },
}
