/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Logo = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type CardsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "cards.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ObjectLogo = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.logo.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Image1 = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media1" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Badge = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "badge.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type CategoriesObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "categories.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type PlansObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "plans.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type HomeLegacyPricingSection = {
  _type: 'homeLegacyPricingSection'
  subtitlePrefix: string
  subtitleHighlight: string
  defaultPlanTitle?: string
  plans: Array<{
    title: string
    price: string
    features: Array<{
      text: string
      active?: boolean
      _key: string
    }>
    description: string
    image?: PlansObjectImage
    primaryButton?: Button
    secondaryButton?: Button
    _key: string
  }>
}

export type HomeLegacyOfferSection = {
  _type: 'homeLegacyOfferSection'
  title: string
  subtitlePrefix: string
  subtitleHighlight: string
  categories: Array<{
    name: string
    activeFeature: string
    inactiveFeatures?: Array<string>
    image?: CategoriesObjectImage
    _key: string
  }>
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  primaryButton?: Button
  secondaryButton?: Button
}

export type HomeLegacyWorkSection = {
  _type: 'homeLegacyWorkSection'
  labelPrefix: string
  labelSuffix: string
  mockupImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  cards: Array<{
    company: string
    description: string
    image?: Image1
    badge?: Badge
    _key: string
  }>
}

export type HomeLegacyTestimonialSection = {
  _type: 'homeLegacyTestimonialSection'
  labelPrefix: string
  labelHighlight: string
  quote: string
  personName: string
  personRole: string
  companyName?: string
  companySubmark?: string
  avatarImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  cardBackgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  playIcon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  brandWordmark?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  brandSeparator?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  brandSubmark?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  stats: Array<{
    value: number
    suffix?: string
    label: string
    _key: string
  }>
}

export type HomeLegacyLogoBarSection = {
  _type: 'homeLegacyLogoBarSection'
  logos: Array<{
    name: string
    logo?: ObjectLogo
    link?: string
    _key: string
  }>
}

export type HomeLegacyHeroSection = {
  _type: 'homeLegacyHeroSection'
  titleLinePrimary: string
  titleLineSecondary: string
  titleLineTertiary: string
  description: string
  ctaButton?: Button
  avatarImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  cards: Array<{
    label: string
    image?: CardsObjectImage
    _key: string
  }>
}

export type HomeContactSection = {
  _type: 'homeContactSection'
  heading: string
  description?: string
  email?: string
  button?: Button
}

export type HomeFaqSection = {
  _type: 'homeFaqSection'
  heading: string
  items: Array<{
    question: string
    answer: string
    _key: string
  }>
}

export type HomeRoiSection = {
  _type: 'homeRoiSection'
  heading: string
  description?: string
  button?: Button
  embedUrl?: string
}

export type HomeUseCasesSection = {
  _type: 'homeUseCasesSection'
  heading: string
  useCases: Array<{
    label: string
    heading: string
    description?: string
    bullets?: Array<string>
    button?: Button
    _key: string
  }>
}

export type HomeOfferSection = {
  _type: 'homeOfferSection'
  heading: string
  subheading?: string
  offers: Array<{
    name: string
    description?: string
    priceNote?: string
    button?: Button
    _key: string
  }>
}

export type HomeProblemSection = {
  _type: 'homeProblemSection'
  heading: string
  description?: string
  problems: Array<string>
}

export type HomeCaseStudiesSection = {
  _type: 'homeCaseStudiesSection'
  heading: string
  subheading?: string
  items: Array<{
    title: string
    summary?: string
    image: ObjectImage
    button?: Button
    _key: string
  }>
}

export type HomeLogosSection = {
  _type: 'homeLogosSection'
  heading?: string
  logos: Array<{
    name: string
    logo: Logo
    link?: string
    _key: string
  }>
}

export type HomeHeroSection = {
  _type: 'homeHeroSection'
  eyebrow?: string
  heading: string
  subheading?: string
  badges?: Array<string>
  primaryButton?: Button
  secondaryButton?: Button
}

export type HomeSeo = {
  _type: 'homeSeo'
  title: string
  description: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  brandName?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  headerNavItems?: Array<{
    label: string
    link?: Link
    _key: string
  }>
  headerCta?: Button
  footerHeading?: string
  footerHighlight?: string
  footerCta?: Button
  footerCtaAvatarImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  footerDescription?: string
  footerLegalText?: string
  footerLegalLinks?: Array<{
    label: string
    link?: Link
    _key: string
  }>
  footerLinkCloudLines?: Array<string>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  locale: 'pl'
  seo?: HomeSeo
  sections: Array<
    | ({
        _key: string
      } & HomeLegacyHeroSection)
    | ({
        _key: string
      } & HomeLegacyLogoBarSection)
    | ({
        _key: string
      } & HomeLegacyTestimonialSection)
    | ({
        _key: string
      } & HomeLegacyWorkSection)
    | ({
        _key: string
      } & HomeLegacyOfferSection)
    | ({
        _key: string
      } & HomeLegacyPricingSection)
    | ({
        _key: string
      } & HomeHeroSection)
    | ({
        _key: string
      } & HomeLogosSection)
    | ({
        _key: string
      } & HomeCaseStudiesSection)
    | ({
        _key: string
      } & HomeProblemSection)
    | ({
        _key: string
      } & HomeOfferSection)
    | ({
        _key: string
      } & HomeUseCasesSection)
    | ({
        _key: string
      } & HomeRoiSection)
    | ({
        _key: string
      } & HomeFaqSection)
    | ({
        _key: string
      } & HomeContactSection)
  >
  publishedAt?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Logo
  | ObjectImage
  | CardsObjectImage
  | ObjectLogo
  | Image1
  | Badge
  | CategoriesObjectImage
  | PlansObjectImage
  | HomeLegacyPricingSection
  | HomeLegacyOfferSection
  | HomeLegacyWorkSection
  | HomeLegacyTestimonialSection
  | HomeLegacyLogoBarSection
  | HomeLegacyHeroSection
  | HomeContactSection
  | HomeFaqSection
  | HomeRoiSection
  | HomeUseCasesSection
  | HomeOfferSection
  | HomeProblemSection
  | HomeCaseStudiesSection
  | HomeLogosSection
  | HomeHeroSection
  | HomeSeo
  | PageReference
  | PostReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | PersonReference
  | Post
  | Person
  | Slug
  | Homepage
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
